
# creating a simple nueral network from scratch

the aim is to create a simple neural network based on a fixed set of 3bit binary input and 1bit odtput pair, and then use it to predict the outcome of an out of set 3bit input

details: create a basic nueral network without any hidden layers, basically a perceptron.

In [3]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

training_inputs = np.array([[0,0,1],
                         [1,1,1],
                         [1,0,1],
                         [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T
print(training_outputs)

[[0]
 [1]
 [1]
 [0]]


In [4]:
np.random.seed(1)

synaptic_weights = 2 * np.random.random((3,1)) - 1

print('Random starting synaptic weights:')
print(synaptic_weights)

Random starting synaptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


iteration 1

In [7]:
for i in range(1):

    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))

print('Outputs after training:')
print(outputs)

Outputs after training:
[[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]


calculations:
taking the first input 0,0,1
doing a dot product with the weights and summing together we get -0.999
putting it in the sigmoid function we get 0.268

training process:
1. taking the inputs and using randomly initialized weights we get the initial nueron outputs
2. calculate the error, basically the difference between output we get and our sample output
3. depending on the severness of the error, adjust the weights
4. repeat this process for a significant amount of times to train the perceptron

error weighted derivative:
    adjust weights by error.input.gradient of sigmoid 
    error = output-sample output
    input, in this case either o or 1
we basically want the correction to be proportional to the input 
the error or difference
and the gradient of the sigmoid is basically pushing it to one of the states 
1 or 0 as the gradient is less at the edges and more in the middle

In [11]:
def sigmoid_der(x):
    return x * (1 - x)

for i in range(20000):

    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    error = training_outputs - outputs
    
    adjustments = error * sigmoid_der(outputs)
    
    synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training: ')
print(synaptic_weights)

print('Outputs after training:')
print(outputs)

Synaptic weights after training: 
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Outputs after training:
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]


In [22]:
e=(training_outputs-outputs)

In [23]:
print(e)

[[-0.00679672]
 [ 0.00554417]
 [ 0.00451484]
 [-0.00553614]]


In [31]:
#training a third time

for i in range(20000):

    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    error = training_outputs - outputs
    
    adjustments = error * sigmoid_der(outputs)
    
    synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training: ')
print(synaptic_weights)

print('Outputs after training:')
print(outputs)

Synaptic weights after training: 
[[11.49345763]
 [-0.2048909 ]
 [-5.54227641]]
Outputs after training:
[[0.00390234]
 [0.99681554]
 [0.99740397]
 [0.00318168]]


In [25]:
e=(training_outputs-outputs)
print(e)

[[-0.00478753]
 [ 0.00390633]
 [ 0.00318343]
 [-0.0039022 ]]


In [26]:
test_input = np.array([[1,0,0]])
outputs = sigmoid(np.dot(test_input, synaptic_weights))

In [27]:
print(outputs)

[[0.99998464]]


In [29]:
print('synaptic weights:')
print(synaptic_weights)

synaptic weights:
[[11.08357409]
 [-0.20536384]
 [-5.33695387]]


In [30]:
test_input = np.array([[0,1,0]])
outputs = sigmoid(np.dot(test_input, synaptic_weights))
print('test 1',outputs)

test_input = np.array([[1,1,0]])
outputs = sigmoid(np.dot(test_input, synaptic_weights))
print("test 2",outputs)

test 1 [[0.44883872]]
test 2 [[0.99998114]]


In [32]:
test_input = np.array([[0,1,1]])
outputs = sigmoid(np.dot(test_input, synaptic_weights))
print("test 3",outputs)

test 3 [[0.00318165]]


In [33]:
test_input = np.array([[0,1,1]])
outputs = sigmoid(np.dot(test_input, synaptic_weights))
print("test 4",int(outputs))

test_input = np.array([[0,1,0]])
outputs = sigmoid(np.dot(test_input, synaptic_weights))
print("test 5",int(outputs))

test 4 0
test 5 0


In [34]:
test_input = np.array([[1,0,1]])
outputs = sigmoid(np.dot(test_input, synaptic_weights))
print("test 6",int(outputs))

test 6 0


In [41]:
test_input = np.array([[1,0,1]])
outputs = sigmoid(np.dot(test_input, synaptic_weights))
out=float(outputs)
print("test 7 : ",round(out))

test 7 :  1
